### ISSUE TITLE
Uncaught Error: Cannot find module './completions'

### ISSUE THREAD

**Issue by jgattegno** [appcelerator/atom-appcelerator-titanium#101]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught Error: Cannot find module './completions'

```
At module.js:472

Error: Cannot find module './completions'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.loadCompletions (/packages/appcelerator-titanium/lib/providers/styleAutoCompleteProvider.js:116:119)
    at Object.getSuggestions (/packages/appcelerator-titanium/lib/providers/styleAutoCompleteProvider.js:30:9)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

### Commands

```
     -1:17.8.0 core:copy (input.hidden-input)
     -1:15.3.0 core:paste (input.hidden-input)
     -1:09.8.0 core:copy (input.hidden-input)
  2x -1:09.6.0 core:backspace (input.hidden-input)
     -1:06.0 editor:newline (input.hidden-input)
     -1:05.8.0 core:paste (input.hidden-input)
     -1:04.5.0 editor:newline (input.hidden-input)
  3x -1:00.5.0 core:backspace (input.hidden-input)
     -0:52.4.0 core:save (input.hidden-input)
     -0:32.4.0 core:backspace (input.hidden-input)
     -0:32 core:move-left (input.hidden-input)
     -0:30.1.0 core:backspace (input.hidden-input)
     -0:28.8.0 core:save (input.hidden-input)
     -0:17.7.0 core:copy (input.hidden-input)
  2x -0:17.5.0 core:paste (input.hidden-input)
     -0:14.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.1.0 
atom-ide-ui 0.9.4 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
```

**Comment by hansemannn** [comment]
Please add steps to reproduce.

**Comment by chrisbowley** [comment]
Please try regenerating the autocomplete suggestions list: go to Settings > Packages > Appcelerator Titanium Settings and toggle Regenerate auto-complete suggestions, then restart Atom.

**Comment by XFelipeXCortesX** [comment]
I`ve tryed to regenerate the autocomplete suggestions but it doesn`t solved the issue.

**Comment by XFelipeXCortesX** [comment]
I`ve tried regenerating the autocomplete suggestions list and the my issue continues.

**Comment by hansemannn** [comment]
@XFelipeXCortesX Did you resolve this by now? We did not see this error with recent versions of the package.

**Comment by ewanharris** [comment]
Closing issue due to inactivity. Please open a new issue if the problem still occurs
