### ISSUE TITLE
Uncaught TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by mjstelly** [appcelerator/atom-appcelerator-titanium#126]
[Enter steps to reproduce:]

1. Open .tss file
2. Edit file to change `paddingLeft` to `padding: {left:'3%'}}`

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'properties' of undefined

```
At /Users/mstelly/.atom/packages/appcelerator-titanium/lib/providers/styleAutoCompleteProvider.js:334

TypeError: Cannot read property 'properties' of undefined
    at Object.getPropertyNameCompletions (/packages/appcelerator-titanium/lib/providers/styleAutoCompleteProvider.js:334:98)
    at Object.getSuggestions (/packages/appcelerator-titanium/lib/providers/styleAutoCompleteProvider.js:51:23)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:58)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:280:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:272:23)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:719:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:785:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1794:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:998:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1650:30)
```

### Commands

```
     -2:15.3.0 find-and-replace:show (input.hidden-input)
     -1:59.4.0 core:save (button.btn.btn-next.disabled)
     -1:58.7.0 core:close (button.btn.btn-next.disabled)
     -1:51.8.0 find-and-replace:show (input.hidden-input)
  2x -1:31 editor:newline (input.hidden-input)
     -1:15.4.0 core:move-down (input.hidden-input)
     -1:11.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:10.9.0 core:backspace (input.hidden-input)
     -1:09.4.0 editor:select-line (input.hidden-input)
     -1:09.0 core:backspace (input.hidden-input)
     -1:07.0 core:save (input.hidden-input)
     -1:06.8.0 linter:lint (atom-text-editor.editor.is-focused)
     -1:00.9.0 core:cancel (button.btn.btn-next)
  2x -0:58.5.0 core:close (input.hidden-input)
     -0:25.6.0 find-and-replace:show (input.hidden-input)
  2x -0:18.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.4.0 
atom-include-path 0.1.0 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
prettier-atom 0.55.2 
```

**Comment by ewanharris** [comment]
Thanks for the report @mjstelly. I've looked into this and the issue seems to lie in the merging of properties by name and then extracting that out when necessary. This issue doesn't occur in the vs code extension which uses a similar code base for the completion support. We're aiming to move to a singular code base for completions between the two so when that's complete this should be fixed properly. I'll push a patch for now though that prevents this error being thrown

**Comment by ewanharris** [comment]
I'm going to close this out as fixed as the issue no longer occurs
