### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mjstelly** [appcelerator/atom-appcelerator-titanium#128]
While troubleshooting [this SDK error](https://stackoverflow.com/questions/9093709/installation-error-install-failed-older-sdk), I replaced my sdk version string values with integer values in my `tiapp.xml` Went from
```<uses-sdk android:minSdkVersion="25" android:targetSdkVersion="27"/>``` to
```<uses-sdk android:minSdkVersion=25 android:targetSdkVersion=27/>```

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/mstelly/.atom/packages/appcelerator-titanium/lib/project.js:165

TypeError: Cannot read property 'name' of undefined
    at Object.appName (/packages/appcelerator-titanium/lib/project.js:165:27)
    at /packages/appcelerator-titanium/lib/index.js:201:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at /packages/appcelerator-titanium/lib/project.js:65:21
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:413:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at NSFWNativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:167:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:276:18)
```

### Commands

```
     -7:49.3.0 core:copy (input.hidden-input)
     -7:43.3.0 core:backspace (input.hidden-input)
     -7:42.1.0 core:save (input.hidden-input)
     -0:17.3.0 core:move-left (input.hidden-input)
  4x -0:16.1.0 core:select-right (input.hidden-input)
     -0:07.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.4.1 
atom-include-path 0.1.0 
busy-signal 1.4.3 
fold-functions 0.11.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
prettier-atom 0.55.2 
```

**Comment by ewanharris** [comment]
Thanks for the report @mjstelly! I can repro this one fairly easily. Will take a lookg
