### ISSUE TITLE
Uncaught TypeError: Cannot read property 'events' of undefined

### ISSUE THREAD

**Issue by bincTW** [appcelerator/atom-appcelerator-titanium#136]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'events' of undefined

```
At /Users/.../.atom/packages/appcelerator-titanium/lib/providers/controllerAutoCompleteProvider.js:192

TypeError: Cannot read property 'events' of undefined
    at /packages/appcelerator-titanium/lib/providers/controllerAutoCompleteProvider.js:192:40
    at Object.getCompletions (/packages/appcelerator-titanium/lib/providers/controllerAutoCompleteProvider.js:201:6)
    at Object.getSuggestions (/packages/appcelerator-titanium/lib/providers/controllerAutoCompleteProvider.js:352:23)
    at n.forEach.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:631262)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:630778)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:630516)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:639049)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:640140)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173759)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504118)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492293)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at BracketMatcher.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:669867)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:259342)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:93878)
```

### Commands

```
 13x -4:02.8.0 core:backspace (input.hidden-input)
     -3:58.8.0 core:save (input.hidden-input)
     -3:52.5.0 appc:build (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  9x -1:52.8.0 core:backspace (input.hidden-input)
     -1:39.6.0 core:save (input.hidden-input)
     -1:06.9.0 editor:newline (input.hidden-input)
  2x -0:54.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:43.6.0 core:backspace (input.hidden-input)
     -0:41.9.0 core:move-right (input.hidden-input)
     -0:16.5.0 core:undo (input.hidden-input)
     -0:15.6.0 core:redo (input.hidden-input)
     -0:13.3.0 core:copy (input.hidden-input)
     -0:12 core:paste (input.hidden-input)
     -0:10.4.0 core:save (input.hidden-input)
     -0:09.2.0 editor:newline (input.hidden-input)
     -0:08.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.5.1 
atom-ide-ui 0.13.0 
```

**Comment by ewanharris** [comment]
@bincTW, do you have any reproducible steps for this? Any codesnippets that reproduce the error for example
