### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dxgx** [appcelerator/atom-appcelerator-titanium#142]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/dariusg/.atom/packages/appcelerator-titanium/lib/appc.js:196

TypeError: Cannot read property 'length' of undefined
    at Object.androidEmulators (/packages/appcelerator-titanium/lib/appc.js:196:56)
    at Object.androidTargets (/packages/appcelerator-titanium/lib/appc.js:233:20)
    at Toolbar.populateAndroidTargets (/packages/appcelerator-titanium/lib/ui/toolbar.jsx:420:23)
    at Toolbar.platformSelectValueDidChange (/packages/appcelerator-titanium/lib/ui/toolbar.jsx:573:10)
    at Select.valueDidChange (/packages/appcelerator-titanium/lib/ui/select.jsx:79:13)
```

### Commands

```
     -0:23.1.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.5.1 
atom-backbone 0.6.1 
atom-beautify 0.33.4 
atom-ctags 5.1.2 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-nodejs-snippets 2.1.1 
atom-runner 2.7.1 
atom-ternjs 0.19.1 
auto-reveal-in-sidebar 0.8.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 2.3.0 
autocomplete-underdash 1.1.0 
build 0.70.0 
build-gulp 0.11.0 
busy-signal 2.0.0 
color-picker 2.3.0 
google-translate-modal-English-Version 2.1.0 
goto-last-edit 0.3.3 
gulp-control 0.5.0 
highlight-selected 0.14.0 
hyperclick 0.0.0 
ide-json 0.2.1 
intentions 1.1.5 
js-hyperclick 1.13.3 
language-titanium 0.5.0 
linter 2.3.0 
linter-jshint 3.1.14 
linter-json-lint 0.1.3 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
markdown-preview-plus 3.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
open-in-browser 0.5.2 
platformio-ide-terminal 2.9.1 
project-manager 3.3.6 
refactor 0.11.5 
remote-sync 4.1.8 
symbols-list 2.5.1 
symbols-view-plus 0.118.2-plus.1 
sync-settings 0.8.6 
tishadow 0.2.3 
titanium-alloy 0.14.6 
titanium-language-javascript 0.48.0 
todo-show 2.3.2 
tool-bar 1.1.11 
toolbar-iconshortcuts 3.17.0 
```

**Comment by ewanharris** [comment]
Based off the code this looks to be due to the emulators prop on info being undefined

**Comment by ewanharris** [comment]
@dxgx, if you're still hitting this error could you please run `appc ti info -t android -o json` and upload the output for me. The emulators prop should always be an empty array by default so I'm wondering if there's another problem that might be causing this error
