### ISSUE TITLE
Uncaught Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jasonfreemanmke** [appcelerator/atom-appcelerator-titanium#158]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.7.0

### Stack Trace

Uncaught Error: Unexpected end of JSON input

```
At events.js:183

Error: Unexpected end of JSON input

    at /packages/appcelerator-titanium/node_modules/suppose/lib/suppose-process.js:93:26)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -0:38.9.0 appc:new (atom-pane.pane.active)
```

### Non-Core Packages

```
appcelerator-titanium 1.7.0 
atom-material-ui 2.1.3 
build 0.70.0 
busy-signal 2.0.1 
hyperclick 0.1.5 
language-babel 2.85.0 
titanium-alloy 0.14.9 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by jasonfreemanmke** [comment]
not sure how to fix this
