### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by RSivakov** [appcelerator/atom-appcelerator-titanium#228]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setEncoding' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'setEncoding' of undefined
    at BufferedProcess.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1123564)
    at BufferedProcess.handleEvents (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125076)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1123084)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122832)
    at Object.getInfo (/packages/appcelerator-titanium/lib/appc.js:46:3)
    at Toolbar.targetSelectValueDidChange (/packages/appcelerator-titanium/lib/ui/toolbar.jsx:609:9)
    at Select.valueDidChange (/packages/appcelerator-titanium/lib/ui/select.jsx:80:13)
```

### Commands

```
     -9:39.1.0 core:backspace (input.hidden-input)
     -9:19.6.0 core:undo (input.hidden-input)
     -9:18.7.0 core:save (input.hidden-input)
     -9:18.2.0 core:select-all (input.hidden-input)
     -9:17.9.0 core:copy (input.hidden-input)
     -9:10.9.0 appc:updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -8:25.1.0 appc:build (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  5x -2:09.5.0 core:backspace (input.hidden-input)
  2x -2:06.3.0 appc:build (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.2.0 appc:generate (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
appcelerator-titanium 1.10.1 
atom-ide-ui 0.13.0 
laravel 0.7.1 
```

**Comment by ewanharris** [comment]
I'm failing to reproduce this, my best guess is that there was an error spawning the command and that's why the [setEncoding](https://github.com/atom/atom/blob/10f7d454edb3d61e3c85f6be1c58122b656c295f/src/buffered-process.js#L149) call fails as stdout/stderr don't exist.

I'm going to close this issue out
