### ISSUE TITLE
Uncaught TypeError: Cannot read property 'populateiOSTargets' of null

### ISSUE THREAD

**Issue by prashantsaini1** [appcelerator/atom-appcelerator-titanium#253]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'populateiOSTargets' of null

```
At /Users/prashant.saini/.atom/packages/appcelerator-titanium/lib/index.js:368

TypeError: Cannot read property 'populateiOSTargets' of null
    at setupTargets (/packages/appcelerator-titanium/lib/index.js:368:19)
    at /packages/appcelerator-titanium/lib/index.js:413:6
    at exit (/packages/appcelerator-titanium/lib/appc.js:54:18)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063586
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
     -0:38.3.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -0:36.4.0 application:new-file (atom-pane.pane)
```

### Non-Core Packages

```
appcelerator-titanium 1.10.1 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-js-console 1.2.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-java 1.2.7 
black-ui 0.3.7 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
color-picker 2.3.0 
copy-find-results 0.2.0 
CP-syntax 0.6.0 
font-viewer 0.3.1 
fonts 3.4.0 
hyperclick 0.1.5 
ide-json 0.2.1 
intentions 1.1.5 
isotope-light-ui 2.3.0 
isotope-ui 2.8.5 
jshint 1.8.6 
jslint 1.5.1 
language-javascript-jsx 0.3.7 
linter 2.3.1 
linter-jslint 11.1.0 
linter-ui-default 1.8.1 
markdown-writer 2.11.9 
metro-syntax 0.3.1 
metro-ui 2.2.2 
native-ui 0.27.0 
now-syntax 0.3.0 
nue-syntax 0.0.2 
pop-syntax 0.5.0 
pretty-json 2.1.2 
slack-like-ui 1.1.1 
slack-ui 0.8.0 
sort-selected-elements 0.1.0 
titanium-alloy 0.14.9 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
two-syntax 0.2.0 
```

**Comment by ewanharris** [comment]
@prashantsaini1 Does this error always occur, or was there something special you did to trigger this error? At a glance it seems like maybe the toolbar was disposed of in some way before the target setup code ran

**Comment by prashantsaini1** [comment]
It happened when I tried to share my screen on [this website](https://app.codesignal.com/test-center) and specifically chosen Atom window only to share. It could be an Atom specific issue but the error dialog reported about this Appc package issue.
