### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by testampat** [appcelerator/atom-appcelerator-titanium#338]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.13.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/v412636/.atom/packages/appcelerator-titanium/node_modules/etch/lib/dom.js:16

RangeError: Maximum call stack size exceeded
    at Object.dom (/packages/appcelerator-titanium/node_modules/etch/lib/dom.js:16:20)
    at ConsoleLog.render (/packages/appcelerator-titanium/lib/ui/console.jsx:41:4)
    at updateSync (/packages/appcelerator-titanium/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/appcelerator-titanium/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326516)
```

### Commands

```
     -3:03.4.0 core:save (input.hidden-input)
  3x -2:47.5.0 core:move-left (input.hidden-input)
     -2:46 core:select-left (input.hidden-input)
     -2:44.7.0 core:save (input.hidden-input)
     -2:22.4.0 core:select-left (input.hidden-input)
     -2:18.9.0 core:select-right (input.hidden-input)
     -2:17.6.0 core:save (input.hidden-input)
     -1:59.4.0 core:move-left (input.hidden-input)
     -1:58.6.0 core:select-down (input.hidden-input)
     -1:57.8.0 core:backspace (input.hidden-input)
     -1:56.2.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -1:55.8.0 core:backspace (input.hidden-input)
     -1:54.5.0 core:save (input.hidden-input)
     -1:31.2.0 core:move-left (input.hidden-input)
     -1:30.8.0 core:select-left (input.hidden-input)
     -1:29.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.13.0 
atom-beautify 0.33.4 
Hydrogen 2.14.6 
teletype 0.13.4 
```

**Comment by ewanharris** [comment]
@testampat, can you please ad some information as to what you were doing when you got this? It looks like it involves the console UI so were you building? Was this before or after you app launched?

**Comment by testampat** [comment]
@ewanharris , From what i understood is this. 
1. This issue happens when u are running app on iphone simulator.
2. On android emulator this issue is not there, also on actual iphone and ios devices this issue is not there.
3. Issue is just running the app from atom UI to simulator
4. App is not able to communicate with any of the appcelerator webservices. it is errorring with error api.appcelerator.com and api.appcelerator.com are not secure.

HTTPRequest The certificate for this server is invalid. You might be connecting to a server that is pretending to be “api.appcelerator.com” which could put your confidential information at risk.

5. I am using APPC analytics, it is trying to upload the crash logs and these error logs in continuous loop and i think thats where this stack size error is coming in.
