### ISSUE TITLE
Failed to activate the appcelerator-titanium package

### ISSUE THREAD

**Issue by grebulon** [appcelerator/atom-appcelerator-titanium#78]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.0.3

### Stack Trace

Failed to activate the appcelerator-titanium package

```
At Cannot read property 'ti:app' of undefined

TypeError: Cannot read property 'ti:app' of undefined
    at Object.loadFileAt (/packages/appcelerator-titanium/lib/tiapp.js:39:21)
    at Object.load (/packages/appcelerator-titanium/lib/tiapp.js:21:8)
    at Object.loadProject (/packages/appcelerator-titanium/lib/index.js:188:9)
    at Object.activate (/packages/appcelerator-titanium/lib/index.js:152:8)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
appcelerator-titanium 1.0.3 
atom-ide-ui 0.7.1 
build 0.59.0 
hyperclick 0.0.0 
ide-java 0.7.0 
ide-json 0.1.0 
ide-php 0.7.4 
ide-python 0.4.0 
titanium-alloy 0.14.6 
titanium-build 0.8.1 
```

**Comment by chrisbowley** [comment]
Thanks, Sorry, looks like a race condition.

**Comment by chrisbowley** [comment]
https://jira.appcelerator.org/browse/ATOM-49

**Comment by ewanharris** [comment]
@prashantsaini1 could I get you to file a new issue in this project with the error. The code that is referenced in this stack trace has long been removed so I'd like to start fresh

**Comment by prashantsaini1** [comment]
Done! Here - https://github.com/appcelerator/atom-appcelerator-titanium/issues/185
