### ISSUE TITLE
appc is not correctly detected in PATH following restart

### ISSUE THREAD

**Issue by olof-nord** [appcelerator/atom-appcelerator-titanium#79]
Following initial install Simulator ran fine, and project compiled. 
However since a restart of Atom appc is no longer detected.

"Failed to spawn command appc. Make sure appc is installed and on your PATH"

<code>
Failed to load resource: net::ERR_FILE_NOT_FOUND nuclicons.ttf
Uncaught Error: Failed to spawn command `appc`. Make sure `appc` is installed and on your PATH
    at BufferedProcess.handleError (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:388:23)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
</code>

Are there any known conflicting packages?

**Comment by chrisbowley** [comment]
You can try launching Atom from Terminal - this should ensure the environment carries over. I'm looking at a permanent fix.

**Comment by olof-nord** [comment]
Many thanks for the advice, I can confirm that it does address the issue.
