### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.appcelerator/install/.version'

### ISSUE THREAD

**Issue by RavindraChherke** [appcelerator/atom-appcelerator-titanium#88]
Getting error after updating to version 1.1.0 

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.2
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/ravindra/.appcelerator/install/.version'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/Users/ravindra/.appcelerator/install/.version'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.generateAutoCompleteSuggestions (/packages/appcelerator-titanium/lib/providers/autoCompleteHelper.js:205:22)
    at /packages/appcelerator-titanium/lib/index.js:300:25
    at exit (/packages/appcelerator-titanium/lib/appc.js:53:18)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  4x -1:56.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
appcelerator-titanium 1.1.0 
atom-beautify 0.30.9 
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by chrisbowley** [comment]
@RavindraChherke with a standard installation you should have an ~/.appcelerator directory containing  the installed versions. The install/.version file simply contains the version number of the selected version. This code hasn't changed in v1.1.0 so I'm not sure why it is suddenly throwing an error. Are you running Atom under a different user to that which installed the Appcelerator tools?

**Comment by RavindraChherke** [comment]
Thank you @chrisbowley .

Seems like my fault. I may have deleted the .version file mistakenly. 

I am have my project built with Titanium SDK version 5.4.0 and now I am trying to upgrade it to SDK 7.
I need to switch between CLI versions frequently to work with both versions. By default Titanium picks the new version so I generally rename the folder. 

I created a .version file and put the version but now getting a different error.

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/ravindra/.appcelerator/install/7.0.1 /package/node_modules/alloy/Alloy/commands/compile/parsers

I use n tool for node version management. I have two version of node 4.2.6  for sdk 5.4 and 8.9.1 for 7.0.1

This Atom Plugin is great but I think for now I have to work on Terminal.
