### ISSUE TITLE
Uncaught TypeError: Cannot set property 'fullversion' of undefined

### ISSUE THREAD

**Issue by michael59** [appcelerator/atom-appcelerator-titanium#89]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot set property 'fullversion' of undefined

```
At /Users/ml/.atom/packages/appcelerator-titanium/lib/appc.js:140

TypeError: Cannot set property 'fullversion' of undefined
    at Object.selectedSdk (/packages/appcelerator-titanium/lib/appc.js:140:19)
    at Object.generateAutoCompleteSuggestions (/packages/appcelerator-titanium/lib/providers/autoCompleteHelper.js:208:42)
    at /packages/appcelerator-titanium/lib/index.js:300:25
    at exit (/packages/appcelerator-titanium/lib/appc.js:53:18)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
appcelerator-titanium 1.1.0 
```

**Comment by chrisbowley** [comment]
It looks like this is a case where the selected SDK has been deleted. Run `appc ti sdk select <SDK_VERSION>` to set the default SDK. I'll add a guard around this to default to the most recent version.
