### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by yankovalera** [appcelerator/atom-appcelerator-titanium#94]
[Enter steps to reproduce:]

1. Typing a class or id in XML 

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '2' of null

```
At /Users/<user>/.atom/packages/appcelerator-titanium/lib/providers/viewAutoCompleteProvider.js:470

TypeError: Cannot read property '2' of null
    at /packages/appcelerator-titanium/lib/providers/viewAutoCompleteProvider.js:470:89
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1097:15)
    at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1052:25)
    at Object.tokenTextForSelector (/packages/appcelerator-titanium/lib/providers/viewAutoCompleteProvider.js:470:14)
    at Object.getAttributeValueCompletions (/packages/appcelerator-titanium/lib/providers/viewAutoCompleteProvider.js:311:19)
    at Object.getSuggestions (/packages/appcelerator-titanium/lib/providers/viewAutoCompleteProvider.js:59:24)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3252:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

### Commands

```
     -0:28.7.0 editor:newline (input.hidden-input)
  4x -0:25.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
appcelerator-titanium 1.1.0 
atom-beautify 0.32.2 
atom-ide-ui 0.9.4 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jshint 3.1.6 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
symbols-list 2.4.1 
sync-settings 0.8.5 
terminal-plus 0.14.5 
ti-create 0.30.0 
underscorejs-snippets 0.2.2 
valign 1.1.3 
```

**Comment by chrisbowley** [comment]
Fixed in https://github.com/appcelerator/atom-appcelerator-titanium/pull/95 / release 1.1.1

**Comment by m1ga** [comment]
Is there an ETA for 1.1.1? Get this error a lot now

**Comment by yankovalera** [comment]
I've copied the fix in my local installation and it's fixed now

**Comment by m1ga** [comment]
did the same on my local machine but I have three others I need to apply the patch. Would be quicker to run the package update :)

**Comment by chrisbowley** [comment]
@m1ga sorry for the delay in release. In the meantime you install directly from the repo: `app install https://github.com/appcelerator/atom-appcelerator-titanium`. Note this will show as v1.1.0.

**Comment by falkolab** [comment]
may be `apm install ...` ?
