### ISSUE TITLE
Uncaught SyntaxError: Unexpected token N in JSON at position 0

### ISSUE THREAD

**Issue by Deepali-s** [appcelerator/atom-appcelerator-titanium#97]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.1
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected token N in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at exit (/packages/appcelerator-titanium/lib/appc.js:52:23)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -2:26.1.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:01.7.0 core:paste (input.hidden-input)
  3x -1:20.3.0 core:confirm (input.hidden-input)
     -1:04.5.0 core:paste (input.hidden-input)
     -1:01.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
appcelerator-titanium 1.1.0 
build 0.70.0 
busy-signal 1.4.3 
hyperclick 0.1.5 
titanium-alloy 0.14.6 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by chrisbowley** [comment]
Please try running `appc info -o json` from Terminal. If the output looks good, set the path to the appc command in the Atom package settings. Otherwise it may be an issue with your environment.

**Comment by hansemannn** [comment]
Looks like it tries to parse a non-JSON object, like `Not found`. We could guard that, but it also looks like a env issue.

**Comment by chrisbowley** [comment]
Agreed, the error messaging should be better.
